#!/usr/bin/env python3
"""Generate src/font8x8.inc : a 8x8 bitmap font (ASCII 0..127) + preview PNG."""
import os, sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
]
TTF = next((p for p in CANDIDATES if os.path.exists(p)), None)
if TTF is None:
    sys.exit("no TTF found")

CELL_W, CELL_H = 8, 8
CAP_ROWS = 7            # rows used by cap height
BIG = 96                # render size for precision

font = ImageFont.truetype(TTF, BIG)


def render(ch):
    m = Image.new("L", (BIG * 2, BIG * 2), 0)
    d = ImageDraw.Draw(m)
    d.text((BIG // 2, BIG // 2), ch, font=font, fill=255)
    return m


def cap_metrics():
    m = render("H")
    bb = m.getbbox()
    return bb[3] - bb[1], bb[2] - bb[0]      # cap height, cap width


CAP_H, CAP_W = cap_metrics()
SCALE = min(CAP_ROWS / CAP_H, CELL_W / CAP_W)

glyphs = []
for code in range(128):
    ch = chr(code) if 32 <= code < 127 else " "
    img = Image.new("L", (CELL_W, CELL_H), 0)
    if code >= 32:
        m = render(ch)
        bb = m.getbbox()
        if bb is not None:
            g = m.crop(bb)
            gw, gh = bb[2] - bb[0], bb[3] - bb[1]
            nw = max(1, min(CELL_W, round(gw * SCALE)))
            nh = max(1, min(CELL_H, round(gh * SCALE)))
            g = g.resize((nw, nh), Image.LANCZOS)
            img.paste(g, ((CELL_W - nw) // 2, CELL_H - nh))
    data = [0] * CELL_H
    px = img.load()
    for y in range(CELL_H):
        b = 0
        for x in range(CELL_W):
            if px[x, y] >= 140:
                b |= 0x80 >> x
        data[y] = b
    glyphs.append(data)

# ---- write NASM include -------------------------------------------------
out = os.path.join(ROOT, "src", "font8x8.inc")
with open(out, "w") as f:
    f.write("; generated by tools/mkfont.py -- do not edit\n")
    f.write("; 8x8 glyphs, 1 byte per row, bit 7 = leftmost pixel, index = ASCII code\n")
    f.write("font8x8:\n")
    for code, g in enumerate(glyphs):
        f.write("    db " + ",".join("0x%02X" % b for b in g) +
                "    ; %3d %r\n" % (code, chr(code) if 32 <= code < 127 else ""))
print("wrote", out, len(glyphs), "glyphs from", os.path.basename(TTF))

# ---- preview -----------------------------------------------------------
S = 6
prev = Image.new("RGB", (CELL_W * S * 16, CELL_H * S * 8), (0, 0, 0))
p = prev.load()
for code, g in enumerate(glyphs):
    ox = (code % 16) * CELL_W * S
    oy = (code // 16) * CELL_H * S
    for y in range(CELL_H):
        for x in range(CELL_W):
            on = g[y] & (0x80 >> x)
            for dy in range(S):
                for dx in range(S):
                    p[ox + x * S + dx, oy + y * S + dy] = (0xE0, 0xE0, 0xE0) if on else (0x10, 0x10, 0x20)
prev.save(os.path.join(HERE, "font_preview.png"))
print("preview ->", os.path.join(HERE, "font_preview.png"))
