#!/usr/bin/env python3
"""Generate src/kbdmap.inc: scancode set 1 -> ascii (unshifted and shifted)."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LOW = {
    0x02: "1", 0x03: "2", 0x04: "3", 0x05: "4", 0x06: "5", 0x07: "6", 0x08: "7",
    0x09: "8", 0x0A: "9", 0x0B: "0", 0x0C: "-", 0x0D: "=", 0x0E: "\b",
    0x0F: "\t", 0x10: "q", 0x11: "w", 0x12: "e", 0x13: "r", 0x14: "t", 0x15: "y",
    0x16: "u", 0x17: "i", 0x18: "o", 0x19: "p", 0x1A: "[", 0x1B: "]", 0x1C: "\n",
    0x1E: "a", 0x1F: "s", 0x20: "d", 0x21: "f", 0x22: "g", 0x23: "h", 0x24: "j",
    0x25: "k", 0x26: "l", 0x27: ";", 0x28: "'", 0x29: "`", 0x2B: "\\",
    0x2C: "z", 0x2D: "x", 0x2E: "c", 0x2F: "v", 0x30: "b", 0x31: "n", 0x32: "m",
    0x33: ",", 0x34: ".", 0x35: "/", 0x39: " ", 0x27: ";",
}
UPP = {
    **LOW,
    0x01: "\x1b", 0x0C: "_", 0x0D: "+", 0x1A: "{", 0x1B: "}", 0x27: ":",
    0x28: '"', 0x29: "~", 0x2B: "|", 0x33: "<", 0x34: ">", 0x35: "?",
    0x0B: ")",
}
for i in range(0x10, 0x1A):          # qwerty
    UPP[i] = LOW[i].upper()
for i in range(0x1E, 0x27):          # asdf
    UPP[i] = LOW[i].upper()
for i in range(0x2C, 0x33):          # zxcvbnm
    UPP[i] = LOW[i].upper()
for i, ch in zip(range(0x02, 0x0C), ")!@#$%^&*("):
    UPP[i] = ch
LOW[0x0B] = "0"


def fmt(c):
    if c == 0:
        return "0"
    # Emit numbers, never quoted escapes: NASM only expands backslash escapes
    # inside double quotes, so "'\\t'" would emit two bytes (backslash + t)
    # and shift every following scancode out of the table.
    if c == "\t":
        return "9"
    if c == "\b":
        return "8"
    if c == "\n":
        return "10"
    if c == "'":
        return "39"
    if c == "\\":
        return "92"
    return "'%s'" % c

lines = ["; generated by tools/mkkbd.py -- scancode set 1 to ascii\n",
         "align 4\nkbd_map:\n"]
for base in range(0, 128, 16):
    row = []
    for s in range(base, base + 16):
        row.append(LOW.get(s, 0))
    lines.append("    db " + ",".join(fmt(c) for c in row) + "\n")
lines.append("align 4\nkbd_map_sh:\n")
for base in range(0, 128, 16):
    row = [UPP.get(s, 0) for s in range(base, base + 16)]
    lines.append("    db " + ",".join(fmt(c) for c in row) + "\n")

out = os.path.join(ROOT, "src", "kbdmap.inc")
open(out, "w").write("".join(lines))
print("wrote", out)
